import { Component, OnInit } from '@angular/core';
import { ModalController } from '@ionic/angular';
import { JobModalPage } from '../job-modal/job-modal.page';

@Component({
  selector: 'app-tab4',
  templateUrl: './tab4.page.html',
  styleUrls: ['./tab4.page.scss'],
})
export class Tab4Page implements OnInit {

  constructor(public modalController: ModalController) { }

  ngOnInit() {

  }
  jobs = [
    { title: "Fullstack Engineer", hirer: "Microsoft", description: "The Operations Applications Group within the Cloud + AI Business Applications Group specializes in best in class solutions enabling businesses to run their end to end operations for the Dynamics 365 line of Enterprise Resource and Planning (ERP) in a Mobile-First/Cloud-First world. Our goal is to enable customers to effectively run their business using the Dynamics 365 products, delivering complete solutions that target the increasing demands of midsize and larger companies. Whether deployed to the cloud or on premise, Dynamics 365 integrates several Microsoft technologies to create a large-scale application. Our culture is inclusive, casual and high energy; our team members come from diverse backgrounds and grounded in our customer needs. Our team is accountable and provides its members a variety of opportunities to learn and grow their careers.",
responsibilities: ["Design, develop, test & support features, experiences & solutions for end-to-end business scenarios over the full stack using modern development technologies", "Collaborate across diverse engineering teams to solve challenging problems for large-scale business SaaS applications", "Accountability for the quality, usability & performance of features", "Debug and handle customer reported issues"],
posted: "Derek"},
    { title: "Testing Engineer", hirer: "Google", description: "At Google, our philosophy is build it, break it and then rebuild it better. That thinking is at the core of how we approach testing at Google. Unlike roles with similar names at the other companies, Test Engineers at Google aren't manual testers -- you write scripts to automate testing and create tools so developers can test their own code. As a Test Engineer, you navigate Google's massive codebase, identify weak spots and constantly design better and creative ways to break software and identify potential problems. You'll have a huge impact on the quality of Google's growing suite of products and services. You use your knowledge of testing and testability to influence better software design, promote proper engineering practice, bug prevention strategies, testability, accessibility, privacy, and other advanced quality concepts across products. Google is and always will be an engineering company. We hire people with a broad set of technical skills who are ready to take on some of technology's greatest challenges and make an impact on millions, if not billions, of users. At Google, engineers not only revolutionize search, they routinely work on massive scalability and storage solutions, large-scale applications and entirely new platforms for developers around the world. From Google Ads to Chrome, Android to YouTube, Social to Local, Google engineers are changing the world one technological achievement after another.",
  responsibilities: ["Lead/collaborate on improving developer and engineering team's test coverage, release velocity and production health", "Work closely with development teams in instrumenting their workflow to build a comprehensive picture of velocity, coverage and quality", "Hands-on ability to automate repeated tasks and build test coverage through existing or new infrastructure", "Write moderately complex code/scripts to test systems, implementing test harnesses and infrastructure as necessary"],
  posted: "Jeremy"},
    { title: "Frontend Developer", hirer: "AWS", description: "Amazon Web Services (AWS) is the world leader in providing a highly reliable, scalable, low-cost infrastructure platform in the cloud that powers hundreds of thousands of businesses in 190 countries around the world! Passionate about building, owning and operating massively scalable systems? Experienced in building and leading teams of highly competent software engineers? Want to make a billion-dollar impact? If so, we have an exciting opportunity for you.The Team: We're an agile, independent team working to build a brand new AWS product. We need developers who are capable of breaking down and solving complex problems. This team will have the opportunity to work on highly visible projects that directly impact hundreds of other teams at Amazon. You will be owning and defining the front end development for a brand new AWS product. Creating the perfect user experience in a web environment requires a blend of technical knowledge, customer obsession and agility. You should be somebody who is interested in how the various components (browsers, networks, APIs, protocols and web servers) work together, and understand how they can be effectively used together to create great user experiences. You will work closely with customers to ensure we are delivering interfaces that make it easy to do complex tasks, without making the experience challenging. You will be part of a small, fast moving team that will have a huge impact on the overall AWS business.",
  responsibilities: ["Experience building rich data-driven web applications", "Experience with modern web technologies and techniques such as HTML5, CSS3, ECMAScript 2016, CSS pre-processors (SASS, Less), JavaScript transpilers (Babel, CoffeeScript, TypeScript), and JavaScript build tools (Browserify, WebPack, Grunt, Gulp)", "Experience in building reusable Web Components", "Experience with modern JavaScript frameworks and libraries such as React, Redux, Vue, Ember, or Angular, along with the knowledge of when to use them", "Experience with Node.js and Java based web applications", "Experience with unit testing framework such as Jest, Jasmine or mocha", "Strong communications skills; you will be required to proactively engage fellow Amazonians both inside and outside of your team.", "Meets/exceeds Amazon’s leadership principles requirements for this role", "Meets/exceeds Amazon’s functional/technical depth and complexity for this role"],
  posted: "Alan"},
    { title: "Backend Developer", hirer: "Redhat", description: "The Red Hat Quality Engineering (QE) team is looking for a Senior Quality Engineer to join us in Boston, MA. In this role, you will make a difference in offerings used by millions of people around the world and help build Red Hat OpenShift, a system changing how development is done, which is built on container technologies and the Kubernetes cluster management system. You’ll gain a deep understanding of a variety of popular technologies, including container technology, Kubernetes, Red Hat OpenStack Platform, and Red Hat Middleware. You’ll make sure our solutions fulfill the highest possible enterprise quality, performance, usability, and supportability criteria. As a Senior Quality Engineer, you will serve as the last instance before applications are released to the public. You'll create and carry out test plans, research new features, and develop automated tests. You’ll need to have the ability to think creatively and adapt to rapid change, as well as the willingness to learn new things.",
  responsibilities: ["Create and review test plans and suggest improvements for product planning processes", "Conduct new feature research and design test cases", "Develop new automated and manual tests; develop frameworks to ease test development and automation to speed up implementation", "Document and advocate the resolution of new bugs with developers and communicate the impact on customers to developers and support", "Participate in and perform root cause of issues to get a starting point to address problems", "Analyze and prioritize quality risks and identify tests required to mitigate them", "Constantly learn new things and maintain an overview of current technologies", "Communicate with other, globally distributed Red Hat OpenShift quality engineers and developers", "Contribute bug fixes to upstream and provide demos of the solutions and technologies", "Help team lead delegate and support the team working on Red Hat OpenShift; serve as a temporary team lead in times of need", "Mentor more junior team members"],
  posted: "Steve"},
    { title: "Systems Engineer", hirer: "Atlassian", description: "Atlassian's Build Engineering team provides the underlying CI services that power the development of our products and services. This team provides the platform that allows Atlassian developers to run thousands of CI builds every single day, while ensuring it remains fast, reliable, and easy to use. The team follows modern development best-practices and apply these to our operational work. They often find themselves innovating with new approaches not seen elsewhere, to meet the ever-changing CI needs of Atlassian developers. Much of their work goes into scaling Atlassian's systems to keep pace with Atlassians own growth. They explicitly set time aside for inventing and experimenting, and are always on the lookout for new technologies and tooling to help achieve the team's and Atlassian's goals. They also consult as a domain authority to software engineers, helping them adopt best practices in their CI pipelines, and debug tricky issues they have with using the platform. Once every couple of months you'll be rostered on-call for a week at at time, to ensure the availability of our most important systems. Due to Atlassians global footprint, you may occasionally travel to our offices in the USA to connect with our Silicon Valley and Austin-based software engineering teams. If you enjoy automating away repetitive tasks, investigating and unclogging bottlenecks, working in areas that span through cloud infrastructure, operating systems, and application environments, then this is the team for you!",
  responsibilities: ["Software development across one or more programming languages, including Java, Kotlin, Groovy, Python, Golang, and Ruby", "Linux system administration", "Automating repetitive tasks with scripts/apps", "SQL and RDBMS management", "Building and maintaining infrastructure in a cloud provider (e.g. AWS)", "Diagnosing and troubleshooting user-facing service outages", "Strong familiarity with CI/CD concepts and tooling (Bamboo, Jenkins, etc.)", "Java software development experience and/or experience supporting Java-based applications", "Experience with container management and microservices architectures such as Docker & Kubernetes", "Exposure to monitoring and centralised logging services", "Experience with configuration management/orchestration tooling (Puppet, Ansible, etc.)", "Experience with infrastructure management tooling (e.g. Terraform)"],
  posted: "John"}
];

selectedJob = {};

async presentModal(i: number) {
  this.selectedJob = this.jobs[i];
  const modal = await this.modalController.create({
    component: JobModalPage,
    componentProps: {
     job: this.selectedJob

    }
  });
  return await modal.present();
}

}
